import { KeyRound } from 'lucide-react'

import { defineTool } from '../../define-tool'

export const tool = defineTool({
  name: 'key-generator',
  path: '/key-generator',
  keywords: [
    'key',
    'keypair',
    'key-pair',
    'public-key',
    'private-key',
    'rsa',
    'ecdsa',
    'ed25519',
    'x25519',
    'hmac',
    'md5',
    'sha1',
    'sha256',
    'sha512',
    'mac',
    'aes',
    'chacha20',
    'symmetric',
    'secret',
    'token',
    'api-key',
    'pem',
    'pkcs8',
    'pkcs1',
    'sec1',
    'spki',
    'jwk',
    'jwks',
    'ssh',
    'ssh-key',
    'fingerprint',
    'der',
    '密钥',
    '密钥对',
    '公钥',
    '私钥',
    '非对称',
    '对称密钥',
    '消息认证码',
    '签名',
    '指纹',
    '令牌',
    '随机',
  ],
  icon: KeyRound,
  component: () => import('./KeyGenerator'),
  createdAt: '2026-09-27',
  // 参数区 + 全格式输出矩阵，两栏都需要宽度
  wide: true,
})
