import { describe, expect, it } from 'vitest'

import { looksLikePem, pemToDer, toPem } from '@/utils/pem'

const DER = new Uint8Array(Array.from({ length: 200 }, (_, i) => i % 251))

describe('toPem', () => {
  it('wraps base64 at 64 columns and terminates with a newline like openssl', () => {
    const pem = toPem('PRIVATE KEY', DER)
    const lines = pem.split('\n')
    expect(lines[0]).toBe('-----BEGIN PRIVATE KEY-----')
    expect(lines.at(-1)).toBe('')
    expect(lines.at(-2)).toBe('-----END PRIVATE KEY-----')
    expect(lines[1]).toHaveLength(64)
    for (const line of lines.slice(1, -2)) {
      expect(line.length).toBeLessThanOrEqual(64)
    }
  })

  it('honours the 70-column wrapping OpenSSH itself uses', () => {
    // 200 字节 → 268 个 base64 字符 → 70 + 70 + 70 + 58
    const lines = toPem('OPENSSH PRIVATE KEY', DER, 70).split('\n')
    expect(lines.slice(1, 4).map((line) => line.length)).toEqual([70, 70, 70])
    expect(lines[4]).toHaveLength(58)
    expect(lines[5]).toBe('-----END OPENSSH PRIVATE KEY-----')
  })

  it('rejects column widths no reader accepts', () => {
    expect(() => toPem('PRIVATE KEY', DER, 8)).toThrowError(
      /columns must be an integer between 16 and 76/,
    )
    expect(() => toPem('PRIVATE KEY', DER, 77)).toThrowError(
      /columns must be an integer between 16 and 76/,
    )
  })

  it('refuses labels that would inject a fake header into the output', () => {
    expect(() => toPem('PRIVATE KEY-----\n-----BEGIN EVIL', DER)).toThrowError(/invalid label/)
    expect(() => toPem('private key', DER)).toThrowError(/invalid label/)
  })
})

describe('pemToDer', () => {
  it('reads back what toPem wrote', () => {
    expect(pemToDer(toPem('PRIVATE KEY', DER))).toEqual({ label: 'PRIVATE KEY', der: DER })
  })

  it('tolerates crlf, surrounding prose and an empty body', () => {
    const pem = toPem('PUBLIC KEY', DER).replace(/\n/g, '\r\n')
    expect(pemToDer(`generated by openssl\r\n${pem}`).der).toEqual(DER)
    expect(pemToDer(toPem('X', new Uint8Array([]))).der).toEqual(new Uint8Array([]))
  })

  it('checks the block type when the caller declares which ones it accepts', () => {
    const pem = toPem('PUBLIC KEY', DER)
    expect(() => pemToDer(pem, ['PRIVATE KEY', 'RSA PRIVATE KEY'])).toThrowError(
      /unexpected type "PUBLIC KEY", expected one of: PRIVATE KEY, RSA PRIVATE KEY/,
    )
  })

  it('rejects concatenated blocks and inputs without a block', () => {
    const pem = toPem('PRIVATE KEY', DER)
    expect(() => pemToDer(pem + pem)).toThrowError(/multiple blocks/)
    expect(() => pemToDer('ssh-ed25519 AAAA')).toThrowError(/no BEGIN\/END block found/)
    expect(() =>
      pemToDer('-----BEGIN PRIVATE KEY-----\n@@@@\n-----END PRIVATE KEY-----'),
    ).toThrowError(/base64/)
  })

  it('detects pem framing without parsing it', () => {
    expect(looksLikePem(toPem('PRIVATE KEY', DER))).toBe(true)
    expect(looksLikePem('MHIBAgEB')).toBe(false)
    expect(looksLikePem('-----BEGIN PRIVATE KEY-----')).toBe(false)
  })
})
